"""
Condensation Link Service — Task 6.3
Handles updating the communications table with condensation status and recalling messages.
"""
import logging
from typing import List, Optional, Dict, Any
from backend.database.db import get_db_connection

logger = logging.getLogger(__name__)

def mark_condensed(com_ids: List[str], condensed_summary: str) -> int:
    """
    Mark a list of messages as condensed in the database.

    Args:
        com_ids: List of com_id strings to mark as condensed.
        condensed_summary: The summary text generated by the LLM.

    Returns:
        int: The number of rows updated.
    """
    if not com_ids:
        return 0

    conn = get_db_connection()
    try:
        cursor = conn.cursor()

        # Prepare the query
        placeholders = ', '.join(['?'] * len(com_ids))
        query = f"""
            UPDATE communications
            SET is_condensed = 1, condensed_summary = ?
            WHERE com_id IN ({placeholders})
        """

        # Execute the update
        # Parameters: summary first, then the list of IDs
        params = [condensed_summary] + com_ids
        cursor.execute(query, params)

        row_count = cursor.rowcount
        conn.commit()

        logger.info(f"Marked {row_count} messages as condensed.")
        return row_count

    except Exception as e:
        logger.error(f"Failed to mark messages as condensed: {e}")
        raise
    finally:
        conn.close()

def recall_message(com_id: str) -> Optional[Dict[str, Any]]:
    """
    Retrieve a single message by its com_id.

    Args:
        com_id: The ID of the message to retrieve.

    Returns:
        dict: A dictionary containing message details, or None if not found.
    """
    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        cursor.execute(
            """
            SELECT com_id, sender, recipient, raw_content,
                   is_condensed, condensed_summary, timestamp
            FROM communications
            WHERE com_id = ?
            """,
            (com_id,)
        )
        row = cursor.fetchone()

        if row:
            return {
                "com_id": row["com_id"],
                "sender": row["sender"],
                "recipient": row["recipient"],
                "raw_content": row["raw_content"],
                "is_condensed": bool(row["is_condensed"]),
                "condensed_summary": row["condensed_summary"],
                "timestamp": row["timestamp"]
            }
        return None
    finally:
        conn.close()
